export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const GET_DOCTOR ="GET_DOCTOR"

export const POST_DOCTOR ="POST_DOCTOR"

export const DELETE_DOCTOR ="DELETE_DOCTOR"

export const UPDATE_DOCTOR ="UPDATE_DOCTOR"

export const LOADING_MEDICINE = "LOADING_MEDICINE"

export const ERROR_MEDICINE ="ERROR_MEDICINE"







